import re
import json

PATTERNS = [
    {"name": "AWS Access Key ID",                    "severity": "critical", "group": "AWS",
     "regex": r"(?<![A-Z0-9])(AKIA|ABIA|ACCA|ASIA)[A-Z0-9]{16}(?![A-Z0-9])"},
    {"name": "AWS Secret Access Key",                "severity": "critical", "group": "AWS",
     "regex": r"(?i)aws.{0,30}secret.{0,30}['\"]([A-Za-z0-9/+=]{40})['\"]"},
    {"name": "AWS Session Token",                    "severity": "critical", "group": "AWS",
     "regex": r"(?i)aws.{0,30}session.{0,30}['\"]([A-Za-z0-9/+=]{100,})['\"]"},
    {"name": "AWS S3 Bucket URL",                    "severity": "medium",   "group": "AWS",
     "regex": r"[a-z0-9.\-]{3,63}\.s3(?:\.[a-z0-9\-]+)?\.amazonaws\.com"},
    {"name": "AWS ARN",                              "severity": "low",      "group": "AWS",
     "regex": r"arn:aws:[a-z0-9\-]+:[a-z0-9\-]*:[0-9]{12}:[^\s'\"]{4,}"},
    {"name": "AWS Cognito Identity Pool",            "severity": "high",     "group": "AWS",
     "regex": r"[a-z]{2}-[a-z]+-[0-9]:[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"},
    {"name": "AWS Cognito User Pool ID",             "severity": "medium",   "group": "AWS",
     "regex": r"(?i)user.?pool.?id.{0,10}['\"]([a-z]{2}-[a-z]+-[0-9]_[A-Za-z0-9]{9})['\"]"},
    {"name": "Google API Key",                       "severity": "high",     "group": "Google",
     "regex": r"AIza[0-9A-Za-z\-_]{35}"},
    {"name": "Google OAuth2 Client Secret",          "severity": "critical", "group": "Google",
     "regex": r"GOCSPX-[0-9A-Za-z\-_]{28}"},
    {"name": "Google OAuth2 Token",                  "severity": "high",     "group": "Google",
     "regex": r"ya29\.[0-9A-Za-z\-_]+"},
    {"name": "Firebase API Key",                     "severity": "high",     "group": "Google",
     "regex": r"(?i)firebase[^'\"\n]{0,40}['\"]AIza[0-9A-Za-z\-_]{35}['\"]"},
    {"name": "Firebase Database URL",                "severity": "medium",   "group": "Google",
     "regex": r"https://[a-zA-Z0-9\-]+\.firebaseio\.com"},
    {"name": "Firebase Config Object",               "severity": "high",     "group": "Google",
     "regex": r"firebaseConfig\s*=\s*\{[^}]{50,800}\}"},
    {"name": "Google Service Account JSON",          "severity": "critical", "group": "Google",
     "regex": r'"type"\s*:\s*"service_account"'},
    {"name": "GCP Project ID",                       "severity": "low",      "group": "Google",
     "regex": r"(?i)project[_\-]?id['\"\s:=]+([a-z][a-z0-9\-]{4,28}[a-z0-9])"},
    {"name": "GitHub PAT Classic",                   "severity": "critical", "group": "GitHub",
     "regex": r"ghp_[0-9A-Za-z]{36}"},
    {"name": "GitHub OAuth Token",                   "severity": "critical", "group": "GitHub",
     "regex": r"gho_[0-9A-Za-z]{36}"},
    {"name": "GitHub App Token",                     "severity": "critical", "group": "GitHub",
     "regex": r"(?:ghs|ghu|ghr)_[0-9A-Za-z]{36}"},
    {"name": "GitHub Fine-Grained Token",            "severity": "critical", "group": "GitHub",
     "regex": r"github_pat_[0-9A-Za-z_]{82}"},
    {"name": "Stripe Live Secret Key",               "severity": "critical", "group": "Stripe",
     "regex": r"sk_live_[0-9A-Za-z]{24,99}"},
    {"name": "Stripe Test Secret Key",               "severity": "medium",   "group": "Stripe",
     "regex": r"sk_test_[0-9A-Za-z]{24,99}"},
    {"name": "Stripe Publishable Key",               "severity": "low",      "group": "Stripe",
     "regex": r"pk_(?:live|test)_[0-9A-Za-z]{24,99}"},
    {"name": "Stripe Webhook Secret",                "severity": "critical", "group": "Stripe",
     "regex": r"whsec_[0-9A-Za-z]{32,99}"},
    {"name": "Stripe Restricted Key",                "severity": "high",     "group": "Stripe",
     "regex": r"rk_(?:live|test)_[0-9A-Za-z]{24,99}"},
    {"name": "Slack Bot Token",                      "severity": "critical", "group": "Slack",
     "regex": r"xoxb-[0-9]{8,13}-[0-9]{8,13}-[0-9A-Za-z]{24}"},
    {"name": "Slack User Token",                     "severity": "critical", "group": "Slack",
     "regex": r"xoxp-[0-9]{8,13}-[0-9]{8,13}-[0-9]{8,13}-[0-9a-f]{32}"},
    {"name": "Slack App Token",                      "severity": "critical", "group": "Slack",
     "regex": r"xapp-\d-[A-Z0-9]+-\d+-[0-9a-f]+"},
    {"name": "Slack Webhook URL",                    "severity": "high",     "group": "Slack",
     "regex": r"https://hooks\.slack\.com/services/T[A-Z0-9]{8,}/B[A-Z0-9]{8,}/[0-9A-Za-z]{24,}"},
    {"name": "Slack Signing Secret",                 "severity": "critical", "group": "Slack",
     "regex": r"(?i)slack.{0,25}sign.{0,25}['\"]([0-9a-f]{32})['\"]"},
    {"name": "Discord Bot Token",                    "severity": "critical", "group": "Discord",
     "regex": r"(?i)discord.{0,25}['\"]([MN][A-Za-z0-9]{23,25}\.[A-Za-z0-9_\-]{6,8}\.[A-Za-z0-9_\-]{27,38})['\"]"},
    {"name": "Discord Webhook URL",                  "severity": "high",     "group": "Discord",
     "regex": r"https://discord(?:app)?\.com/api/webhooks/[0-9]+/[0-9A-Za-z_\-]+"},
    {"name": "Discord Client Secret",                "severity": "critical", "group": "Discord",
     "regex": r"(?i)discord.{0,35}client.?secret.{0,15}['\"]([a-zA-Z0-9_\-]{30,})['\"]"},
    {"name": "Discord Verify Key",                   "severity": "high",     "group": "Discord",
     "regex": r"(?i)(?:discord.{0,25}verify.{0,10}key|verifyKey).{0,15}['\"]([a-f0-9]{64})['\"]"},
    {"name": "Twilio Account SID",                   "severity": "high",     "group": "Twilio",
     "regex": r"\bAC[0-9a-f]{32}\b"},
    {"name": "Twilio Auth Token",                    "severity": "critical", "group": "Twilio",
     "regex": r"(?i)twilio.{0,25}auth.{0,25}['\"]([0-9a-f]{32})['\"]"},
    {"name": "SendGrid API Key",                     "severity": "critical", "group": "Email",
     "regex": r"SG\.[0-9A-Za-z\-_]{22}\.[0-9A-Za-z\-_]{43}"},
    {"name": "Mailgun API Key",                      "severity": "critical", "group": "Email",
     "regex": r"\bkey-[0-9a-zA-Z]{32}\b"},
    {"name": "Postmark Server Token",                "severity": "critical", "group": "Email",
     "regex": r"(?i)postmark.{0,25}['\"]([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})['\"]"},
    {"name": "Resend API Key",                       "severity": "critical", "group": "Email",
     "regex": r"\bre_[0-9A-Za-z]{32,}\b"},
    {"name": "Brevo API Key",                        "severity": "critical", "group": "Email",
     "regex": r"xkeysib-[a-f0-9]{64}-[A-Za-z0-9]{16}"},
    {"name": "Mailchimp API Key",                    "severity": "critical", "group": "Email",
     "regex": r"[0-9a-f]{32}-us[0-9]{1,2}"},
    {"name": "Mailjet API Key",                      "severity": "critical", "group": "Email",
     "regex": r"(?i)mailjet.{0,25}(?:api.?key|public.?key).{0,10}['\"]([a-f0-9]{32})['\"]"},
    {"name": "Mailjet Secret Key",                   "severity": "critical", "group": "Email",
     "regex": r"(?i)mailjet.{0,25}(?:secret|private).{0,10}['\"]([a-f0-9]{32})['\"]"},
    {"name": "SparkPost API Key",                    "severity": "critical", "group": "Email",
     "regex": r"(?i)sparkpost.{0,25}['\"]([a-f0-9]{40})['\"]"},
    {"name": "Klaviyo API Key",                      "severity": "critical", "group": "Marketing",
     "regex": r"(?i)klaviyo.{0,25}['\"]([A-Za-z0-9]{6}-[A-Za-z0-9]{6}-[A-Za-z0-9]{6})['\"]"},
    {"name": "Klaviyo Public Key",                   "severity": "medium",   "group": "Marketing",
     "regex": r"\bpk_[A-Za-z0-9]{30,}\b"},
    {"name": "Cloudflare API Key",                   "severity": "critical", "group": "Cloudflare",
     "regex": r"(?i)cloudflare.{0,25}['\"]([0-9a-f]{37})['\"]"},
    {"name": "Cloudflare API Token",                 "severity": "critical", "group": "Cloudflare",
     "regex": r"(?i)cf.{0,15}(?:api.?token|auth.?token).{0,15}['\"]([a-zA-Z0-9_\-]{40})['\"]"},
    {"name": "Azure Storage Connection",             "severity": "critical", "group": "Azure",
     "regex": r"DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{88}"},
    {"name": "Azure AD Client Secret",               "severity": "critical", "group": "Azure",
     "regex": r"(?i)azure.{0,25}(?:client.?secret|password).{0,15}['\"]([^'\"]{20,})['\"]"},
    {"name": "MongoDB Connection String",            "severity": "critical", "group": "Database",
     "regex": r"mongodb(?:\+srv)?://[^:'\"\s]{2,}:[^@'\"\s]{2,}@[^/'\"\s\]]+"},
    {"name": "PostgreSQL Connection String",         "severity": "critical", "group": "Database",
     "regex": r"postgres(?:ql)?://[^:'\"\s]{2,}:[^@'\"\s]{2,}@[^/'\"\s\]]+"},
    {"name": "MySQL Connection String",              "severity": "critical", "group": "Database",
     "regex": r"mysql://[^:'\"\s]{2,}:[^@'\"\s]{2,}@[^/'\"\s\]]+"},
    {"name": "Redis Connection String",              "severity": "high",     "group": "Database",
     "regex": r"redis://(?:[^:'\"\s]+:[^@'\"\s]+@)?[^/'\"\s\]]+"},
    {"name": "Redis TLS Connection",                 "severity": "high",     "group": "Database",
     "regex": r"rediss://(?:[^:'\"\s]+:[^@'\"\s]+@)?[^/'\"\s\]]+"},
    {"name": "Supabase URL",                         "severity": "medium",   "group": "Supabase",
     "regex": r"https://[a-z0-9]{20}\.supabase\.(?:co|net|io)"},
    {"name": "Supabase Anon Key",                    "severity": "high",     "group": "Supabase",
     "regex": r"eyJ[A-Za-z0-9_\-]{40,}\.eyJ[A-Za-z0-9_\-]{40,}\.[A-Za-z0-9_\-]{10,}"},
    {"name": "Supabase Service Role Key",            "severity": "critical", "group": "Supabase",
     "regex": r"(?i)supabase.{0,25}service.{0,10}(?:role.{0,5})?key.{0,10}['\"]([A-Za-z0-9_\-\.]{100,})['\"]"},
    {"name": "PlanetScale Database URL",             "severity": "critical", "group": "Database",
     "regex": r"mysql://[^:'\"\s]+:[^@'\"\s]+@[^/'\"\s\]]*\.psdb\.cloud[^'\"\s\]]*"},
    {"name": "Neon Database URL",                    "severity": "critical", "group": "Database",
     "regex": r"postgres(?:ql)?://[^:'\"\s]+:[^@'\"\s]+@[^/'\"\s\]]*\.neon\.tech[^'\"\s\]]*"},
    {"name": "Turso Database URL",                   "severity": "critical", "group": "Database",
     "regex": r"libsql://[a-zA-Z0-9\-]+\.turso\.io"},
    {"name": "Upstash Redis URL",                    "severity": "critical", "group": "Database",
     "regex": r"rediss?://[^:'\"\s]+:[^@'\"\s]+@[^/'\"\s\]]*\.upstash\.io"},
    {"name": "Snowflake Connection",                 "severity": "critical", "group": "Database",
     "regex": r"(?i)snowflake.{0,30}(?:account|password|private.?key).{0,20}['\"]([^'\"]{16,})['\"]"},
    {"name": "Databricks Token",                     "severity": "critical", "group": "Database",
     "regex": r"dapi[0-9a-f]{32}"},
    {"name": "RSA Private Key",                      "severity": "critical", "group": "Cryptography",
     "regex": r"-----BEGIN (?:RSA )?PRIVATE KEY-----"},
    {"name": "EC Private Key",                       "severity": "critical", "group": "Cryptography",
     "regex": r"-----BEGIN EC PRIVATE KEY-----"},
    {"name": "OpenSSH Private Key",                  "severity": "critical", "group": "Cryptography",
     "regex": r"-----BEGIN OPENSSH PRIVATE KEY-----"},
    {"name": "PGP Private Key",                      "severity": "critical", "group": "Cryptography",
     "regex": r"-----BEGIN PGP PRIVATE KEY BLOCK-----"},
    {"name": "JSON Web Token",                       "severity": "medium",   "group": "Auth",
     "regex": r"\beyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\b"},
    {"name": "Bearer Token",                         "severity": "high",     "group": "Auth",
     "regex": r"(?i)(?:authorization|auth)\s*[:=]\s*['\"]?Bearer\s+([A-Za-z0-9\-_\.=+/]{20,})"},
    {"name": "Hardcoded Password",                   "severity": "high",     "group": "Auth",
     "regex": r"(?i)(?:password|passwd|pwd)\s*[:=]\s*['\"]([^'\"]{8,100})['\"]"},
    {"name": "Hardcoded Secret or Key",              "severity": "high",     "group": "Auth",
     "regex": r"(?i)(?:secret|api[_\-]?key|apikey|access[_\-]?key|auth[_\-]?token)\s*[:=]\s*['\"]([^'\"]{16,200})['\"]"},
    {"name": "NPM Token",                            "severity": "critical", "group": "DevOps",
     "regex": r"\bnpm_[A-Za-z0-9]{36}\b"},
    {"name": "PyPI API Token",                       "severity": "critical", "group": "DevOps",
     "regex": r"\bpypi-[A-Za-z0-9_\-]{50,}\b"},
    {"name": "Vercel Token",                         "severity": "critical", "group": "DevOps",
     "regex": r"(?i)vercel.{0,25}['\"]([A-Za-z0-9]{24})['\"]"},
    {"name": "Doppler Token",                        "severity": "critical", "group": "DevOps",
     "regex": r"dp\.pt\.[A-Za-z0-9]{40,}"},
    {"name": "HashiCorp Vault Token",                "severity": "critical", "group": "DevOps",
     "regex": r"(?i)vault.{0,25}token.{0,15}['\"]([a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12})['\"]"},
    {"name": "Terraform Cloud Token",                "severity": "critical", "group": "DevOps",
     "regex": r"(?i)terraform.{0,25}['\"]([A-Za-z0-9\.]{14}\.atlasv1\.[A-Za-z0-9]{60,})['\"]"},
    {"name": "CircleCI API Token",                   "severity": "high",     "group": "DevOps",
     "regex": r"(?i)circle.?ci.{0,25}['\"]([a-f0-9]{40})['\"]"},
    {"name": "OpenAI API Key",                       "severity": "critical", "group": "AI",
     "regex": r"\bsk-(?:proj-|org-)?[A-Za-z0-9]{20,}T3BlbkFJ[A-Za-z0-9]{20,}\b"},
    {"name": "OpenAI API Key New",                   "severity": "critical", "group": "AI",
     "regex": r"\bsk-proj-[A-Za-z0-9_\-]{40,}\b"},
    {"name": "Anthropic API Key",                    "severity": "critical", "group": "AI",
     "regex": r"\bsk-ant-(?:api03-)?[A-Za-z0-9_\-]{93,}\b"},
    {"name": "HuggingFace API Token",                "severity": "critical", "group": "AI",
     "regex": r"\bhf_[A-Za-z0-9]{34}\b"},
    {"name": "Groq API Key",                         "severity": "critical", "group": "AI",
     "regex": r"\bgsk_[A-Za-z0-9]{52}\b"},
    {"name": "Cohere API Key",                       "severity": "critical", "group": "AI",
     "regex": r"(?i)cohere.{0,25}['\"]([A-Za-z0-9]{40})['\"]"},
    {"name": "Replicate API Token",                  "severity": "critical", "group": "AI",
     "regex": r"\br8_[A-Za-z0-9]{38}\b"},
    {"name": "Pinecone API Key",                     "severity": "critical", "group": "AI",
     "regex": r"(?i)pinecone.{0,25}['\"]([a-f0-9\-]{36,})['\"]"},
    {"name": "Mistral API Key",                      "severity": "critical", "group": "AI",
     "regex": r"(?i)mistral.{0,25}['\"]([A-Za-z0-9]{32})['\"]"},
    {"name": "Together AI Key",                      "severity": "critical", "group": "AI",
     "regex": r"(?i)together.{0,25}['\"]([A-Za-z0-9]{64})['\"]"},
    {"name": "Perplexity API Key",                   "severity": "critical", "group": "AI",
     "regex": r"pplx-[A-Za-z0-9]{48}"},
    {"name": "ElevenLabs API Key",                   "severity": "critical", "group": "AI",
     "regex": r"(?i)eleven.?labs.{0,25}['\"]([a-f0-9]{32})['\"]"},
    {"name": "Stability AI Key",                     "severity": "critical", "group": "AI",
     "regex": r"sk-[A-Za-z0-9]{48}"},
    {"name": "Stripe Live Secret Key",               "severity": "critical", "group": "Payments",
     "regex": r"sk_live_[0-9A-Za-z]{24,99}"},
    {"name": "PayPal Access Token",                  "severity": "critical", "group": "Payments",
     "regex": r"access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}"},
    {"name": "Tebex Secret Key",                     "severity": "critical", "group": "Payments",
     "regex": r"(?i)tebex.{0,25}(?:secret|key).{0,15}['\"]([a-zA-Z0-9]{32,})['\"]"},
    {"name": "Shopify Admin Token",                  "severity": "critical", "group": "Shopify",
     "regex": r"\bshpat_[0-9A-Fa-f]{32}\b"},
    {"name": "Shopify Private App",                  "severity": "critical", "group": "Shopify",
     "regex": r"\bshppa_[0-9A-Fa-f]{32}\b"},
    {"name": "Shopify Storefront Token",             "severity": "medium",   "group": "Shopify",
     "regex": r"\bshpss_[0-9A-Fa-f]{32}\b"},
    {"name": "Square Access Token",                  "severity": "critical", "group": "Payments",
     "regex": r"\bsq0[a-z]{3}-[0-9A-Za-z_\-]{22,43}\b"},
    {"name": "LemonSqueezy API Key",                 "severity": "critical", "group": "Payments",
     "regex": r"(?i)lemon.{0,25}squeezy.{0,25}['\"]([A-Za-z0-9]{40,})['\"]"},
    {"name": "Plaid Client Secret",                  "severity": "critical", "group": "Payments",
     "regex": r"(?i)plaid.{0,25}(?:secret|client_secret).{0,10}['\"]([a-z0-9]{30,})['\"]"},
    {"name": "Plaid Client ID",                      "severity": "medium",   "group": "Payments",
     "regex": r"(?i)plaid.{0,25}client.?id.{0,10}['\"]([a-z0-9]{24})['\"]"},
    {"name": "Wise API Token",                       "severity": "critical", "group": "Payments",
     "regex": r"(?i)wise.{0,25}(?:api.?token|token).{0,10}['\"]([A-Za-z0-9\-]{36})['\"]"},
    {"name": "Linear API Key",                       "severity": "critical", "group": "Productivity",
     "regex": r"\blin_api_[A-Za-z0-9]{40}\b"},
    {"name": "Notion API Token",                     "severity": "critical", "group": "Productivity",
     "regex": r"\bsecret_[A-Za-z0-9]{43}\b"},
    {"name": "Airtable API Key",                     "severity": "critical", "group": "Productivity",
     "regex": r"\bpat[A-Za-z0-9]{14,}\b"},
    {"name": "Asana Access Token",                   "severity": "critical", "group": "Productivity",
     "regex": r"(?i)asana.{0,25}['\"]([0-9]{1,10}/[a-f0-9]{32})['\"]"},
    {"name": "Monday.com API Token",                 "severity": "critical", "group": "Productivity",
     "regex": r"(?i)monday.{0,25}['\"]([A-Za-z0-9]{64})['\"]"},
    {"name": "ClickUp API Token",                    "severity": "critical", "group": "Productivity",
     "regex": r"\bpk_[0-9]{8}_[A-Z0-9]{32}\b"},
    {"name": "Jira API Token",                       "severity": "high",     "group": "Productivity",
     "regex": r"(?i)jira.{0,25}['\"]([A-Za-z0-9]{24})['\"]"},
    {"name": "Sentry DSN",                           "severity": "medium",   "group": "Monitoring",
     "regex": r"https://[0-9a-f]{32}@(?:o[0-9]+\.)?ingest(?:\.[a-z]+)?\.sentry\.io/[0-9]+"},
    {"name": "Datadog API Key",                      "severity": "high",     "group": "Monitoring",
     "regex": r"(?i)datadog.{0,25}api.?key.{0,15}['\"]([a-f0-9]{32})['\"]"},
    {"name": "Datadog App Key",                      "severity": "high",     "group": "Monitoring",
     "regex": r"(?i)datadog.{0,25}app.?key.{0,15}['\"]([a-f0-9]{40})['\"]"},
    {"name": "New Relic License Key",                "severity": "high",     "group": "Monitoring",
     "regex": r"\bNRAK-[A-Z0-9]{27}\b"},
    {"name": "Rollbar Access Token",                 "severity": "high",     "group": "Monitoring",
     "regex": r"(?i)rollbar.{0,25}['\"]([a-f0-9]{32})['\"]"},
    {"name": "Bugsnag API Key",                      "severity": "medium",   "group": "Monitoring",
     "regex": r"(?i)bugsnag.{0,25}['\"]([a-f0-9]{32})['\"]"},
    {"name": "LogRocket App ID",                     "severity": "medium",   "group": "Monitoring",
     "regex": r"(?i)logrocket.{0,25}['\"]([a-zA-Z0-9]{6}/[a-zA-Z0-9_\-]{6,40})['\"]"},
    {"name": "Sumo Logic Access Key",                "severity": "critical", "group": "Monitoring",
     "regex": r"(?i)sumo.?logic.{0,25}access.?key.{0,10}['\"]([A-Za-z0-9]{64})['\"]"},
    {"name": "Mapbox Public Token",                  "severity": "medium",   "group": "Mapping",
     "regex": r"\bpk\.eyJ1IjoiW[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+"},
    {"name": "Mapbox Secret Token",                  "severity": "critical", "group": "Mapping",
     "regex": r"\bsk\.eyJ1IjoiW[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+"},
    {"name": "HERE Maps API Key",                    "severity": "high",     "group": "Mapping",
     "regex": r"(?i)here.{0,25}['\"]([A-Za-z0-9_\-]{43})['\"]"},
    {"name": "Pusher App Secret",                    "severity": "critical", "group": "Realtime",
     "regex": r"(?i)pusher.{0,25}(?:app.?secret|secret).{0,15}['\"]([a-zA-Z0-9]{20,})['\"]"},
    {"name": "Pusher App Key",                       "severity": "medium",   "group": "Realtime",
     "regex": r"(?i)pusher.{0,25}(?:app.?key|key).{0,15}['\"]([a-zA-Z0-9]{20})['\"]"},
    {"name": "Ably API Key",                         "severity": "critical", "group": "Realtime",
     "regex": r"[a-zA-Z0-9_\-]{8,}\.[a-zA-Z0-9_\-]{4,}:[a-zA-Z0-9_\-]{16,}"},
    {"name": "Telegram Bot Token",                   "severity": "critical", "group": "Messaging",
     "regex": r"\b[0-9]{8,10}:[A-Za-z0-9_\-]{35}\b"},
    {"name": "Twitch Client Secret",                 "severity": "critical", "group": "Streaming",
     "regex": r"(?i)twitch.{0,25}client.?secret.{0,10}['\"]([a-z0-9]{30})['\"]"},
    {"name": "Twitch OAuth Token",                   "severity": "critical", "group": "Streaming",
     "regex": r"oauth:[a-z0-9]{30}"},
    {"name": "Mux Secret Key",                       "severity": "critical", "group": "Media",
     "regex": r"(?i)mux.{0,25}secret.{0,10}['\"]([A-Za-z0-9+/]{32,})['\"]"},
    {"name": "Mux Token Secret",                     "severity": "critical", "group": "Media",
     "regex": r"(?i)mux.{0,25}token.?secret.{0,10}['\"]([a-zA-Z0-9+/]{20,})['\"]"},
    {"name": "Auth0 Client Secret",                  "severity": "critical", "group": "Auth",
     "regex": r"(?i)auth0.{0,25}client.?secret.{0,10}['\"]([A-Za-z0-9_\-]{40,})['\"]"},
    {"name": "Auth0 Management Token",               "severity": "critical", "group": "Auth",
     "regex": r"(?i)auth0.{0,25}management.?token.{0,10}['\"]([A-Za-z0-9_\-\.]{40,})['\"]"},
    {"name": "Okta API Token",                       "severity": "critical", "group": "Auth",
     "regex": r"00[a-zA-Z0-9_\-]{38}"},
    {"name": "WorkOS API Key",                       "severity": "critical", "group": "Auth",
     "regex": r"(?i)workos.{0,25}['\"]([a-zA-Z0-9_]{30,})['\"]"},
    {"name": "Stytch Project Secret",                "severity": "critical", "group": "Auth",
     "regex": r"secret-(?:test|live)-[A-Za-z0-9]{28}"},
    {"name": "Stytch Project ID",                    "severity": "medium",   "group": "Auth",
     "regex": r"project-(?:test|live)-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"},
    {"name": "Clerk Secret Key",                     "severity": "critical", "group": "Auth",
     "regex": r"sk_(?:test|live)_[A-Za-z0-9]{40,}"},
    {"name": "Clerk Publishable Key",                "severity": "low",      "group": "Auth",
     "regex": r"pk_(?:test|live)_[A-Za-z0-9]{40,}"},
    {"name": "HubSpot API Key",                      "severity": "critical", "group": "CRM",
     "regex": r"(?i)hubspot.{0,25}['\"]([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})['\"]"},
    {"name": "HubSpot Access Token",                 "severity": "critical", "group": "CRM",
     "regex": r"pat-(?:na|eu|au)1-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"},
    {"name": "Salesforce Access Token",              "severity": "critical", "group": "CRM",
     "regex": r"00D[A-Za-z0-9]{15}![A-Za-z0-9_.]{80,}"},
    {"name": "Intercom Access Token",                "severity": "critical", "group": "CRM",
     "regex": r"(?i)intercom.{0,25}access.?token.{0,10}['\"]([A-Za-z0-9_]{64,})['\"]"},
    {"name": "Zendesk API Token",                    "severity": "critical", "group": "CRM",
     "regex": r"(?i)zendesk.{0,25}(?:api.?token|token).{0,10}['\"]([A-Za-z0-9]{40,})['\"]"},
    {"name": "Freshdesk API Key",                    "severity": "critical", "group": "CRM",
     "regex": r"(?i)freshdesk.{0,25}['\"]([A-Za-z0-9]{20})['\"]"},
    {"name": "Segment Write Key",                    "severity": "high",     "group": "Analytics",
     "regex": r"(?i)segment.{0,25}write.?key.{0,10}['\"]([A-Za-z0-9]{32})['\"]"},
    {"name": "Amplitude API Key",                    "severity": "high",     "group": "Analytics",
     "regex": r"(?i)amplitude.{0,25}api.?key.{0,10}['\"]([a-f0-9]{32})['\"]"},
    {"name": "Mixpanel Token",                       "severity": "medium",   "group": "Analytics",
     "regex": r"(?i)mixpanel.{0,25}token.{0,10}['\"]([a-f0-9]{32})['\"]"},
    {"name": "PostHog API Key",                      "severity": "high",     "group": "Analytics",
     "regex": r"phc_[A-Za-z0-9]{43}"},
    {"name": "Hotjar Site ID",                       "severity": "low",      "group": "Analytics",
     "regex": r"(?i)hotjar.{0,25}site.?id.{0,10}['\"]([0-9]{5,10})['\"]"},
    {"name": "FullStory Org ID",                     "severity": "low",      "group": "Analytics",
     "regex": r"(?i)fullstory.{0,25}org.?id.{0,10}['\"]([A-Z0-9]{6,10})['\"]"},
    {"name": "Algolia App ID",                       "severity": "medium",   "group": "Search",
     "regex": r"(?i)algolia.{0,25}app.?id.{0,10}['\"]([A-Z0-9]{10})['\"]"},
    {"name": "Algolia API Key",                      "severity": "high",     "group": "Search",
     "regex": r"(?i)algolia.{0,25}api.?key.{0,10}['\"]([a-f0-9]{32})['\"]"},
    {"name": "Algolia Admin API Key",                "severity": "critical", "group": "Search",
     "regex": r"(?i)algolia.{0,25}admin.{0,10}key.{0,10}['\"]([a-f0-9]{32})['\"]"},
    {"name": "Contentful Delivery Key",              "severity": "high",     "group": "CMS",
     "regex": r"(?i)contentful.{0,25}(?:delivery|access).?key.{0,10}['\"]([A-Za-z0-9_\-]{43})['\"]"},
    {"name": "Contentful Management Token",          "severity": "critical", "group": "CMS",
     "regex": r"CFPAT-[A-Za-z0-9_\-]{43}"},
    {"name": "Sanity Project ID",                    "severity": "medium",   "group": "CMS",
     "regex": r"(?i)sanity.{0,25}project.?id.{0,10}['\"]([a-z0-9]{8})['\"]"},
    {"name": "Sanity Token",                         "severity": "critical", "group": "CMS",
     "regex": r"(?i)sanity.{0,25}token.{0,10}['\"](sk[A-Za-z0-9]{90,})['\"]"},
    {"name": "Webflow API Token",                    "severity": "critical", "group": "CMS",
     "regex": r"(?i)webflow.{0,25}(?:api.?token|token).{0,10}['\"]([a-f0-9]{64})['\"]"},
    {"name": "LaunchDarkly SDK Key",                 "severity": "critical", "group": "FeatureFlags",
     "regex": r"sdk-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"},
    {"name": "LaunchDarkly Client Key",              "severity": "medium",   "group": "FeatureFlags",
     "regex": r"(?i)launchdarkly.{0,25}client.?side.?id.{0,10}['\"]([a-f0-9]{24})['\"]"},
    {"name": "Split.io SDK Key",                     "severity": "critical", "group": "FeatureFlags",
     "regex": r"(?i)split.?io.{0,25}['\"]([A-Za-z0-9_\-]{40,})['\"]"},
    {"name": "Unleash API Token",                    "severity": "critical", "group": "FeatureFlags",
     "regex": r"(?i)unleash.{0,25}(?:api.?token|token).{0,10}['\"]([A-Za-z0-9_:\-]{20,})['\"]"},
    {"name": "OneSignal App ID",                     "severity": "medium",   "group": "Notifications",
     "regex": r"(?i)onesignal.{0,25}app.?id.{0,10}['\"]([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})['\"]"},
    {"name": "OneSignal API Key",                    "severity": "critical", "group": "Notifications",
     "regex": r"(?i)onesignal.{0,25}api.?key.{0,10}['\"]([A-Za-z0-9_\-]{40,})['\"]"},
    {"name": "Courier API Key",                      "severity": "critical", "group": "Notifications",
     "regex": r"(?i)courier.{0,25}(?:api.?key|auth.?token).{0,10}['\"]([A-Za-z0-9_\-]{40,})['\"]"},
    {"name": "Novu API Key",                         "severity": "critical", "group": "Notifications",
     "regex": r"(?i)novu.{0,25}api.?key.{0,10}['\"]([A-Za-z0-9_\-]{40,})['\"]"},
    {"name": "Braintree Production Key",             "severity": "critical", "group": "Payments",
     "regex": r"(?i)braintree.{0,25}private.?key.{0,10}['\"]([a-f0-9]{32})['\"]"},
    {"name": "Braintree Public Key",                 "severity": "medium",   "group": "Payments",
     "regex": r"(?i)braintree.{0,25}public.?key.{0,10}['\"]([a-f0-9]{8})['\"]"},
    {"name": "Zoom JWT Secret",                      "severity": "critical", "group": "Video",
     "regex": r"(?i)zoom.{0,25}(?:jwt.?secret|secret).{0,10}['\"]([A-Za-z0-9_\-]{32,})['\"]"},
    {"name": "Zoom API Key",                         "severity": "high",     "group": "Video",
     "regex": r"(?i)zoom.{0,25}api.?key.{0,10}['\"]([A-Za-z0-9_\-]{22})['\"]"},
    {"name": "Figma API Token",                      "severity": "critical", "group": "Design",
     "regex": r"(?i)figma.{0,25}(?:access.?token|token).{0,10}['\"]([a-zA-Z0-9\-_]{43})['\"]"},
    {"name": "Retool API Token",                     "severity": "critical", "group": "DevTools",
     "regex": r"(?i)retool.{0,25}(?:api.?token|token).{0,10}['\"]([A-Za-z0-9\-_]{32,})['\"]"},
    {"name": "SendBird API Token",                   "severity": "critical", "group": "Messaging",
     "regex": r"(?i)sendbird.{0,25}(?:api.?token|master.?api.?key).{0,10}['\"]([A-Za-z0-9]{32,})['\"]"},
    {"name": "Whatsapp Business Token",              "severity": "critical", "group": "Messaging",
     "regex": r"(?i)whatsapp.{0,25}(?:access.?token|token).{0,10}['\"]([A-Za-z0-9]{100,})['\"]"},
    {"name": "BrowserStack Access Key",              "severity": "high",     "group": "Testing",
     "regex": r"(?i)browserstack.{0,25}access.?key.{0,10}['\"]([A-Za-z0-9]{20})['\"]"},
    {"name": "Help Scout API Key",                   "severity": "critical", "group": "Support",
     "regex": r"(?i)helpscout.{0,25}(?:api.?key|token).{0,10}['\"]([A-Za-z0-9]{32})['\"]"},
    {"name": "Talkdesk API Key",                     "severity": "critical", "group": "Support",
     "regex": r"(?i)talkdesk.{0,25}(?:api.?key|token).{0,10}['\"]([A-Za-z0-9_\-]{32,})['\"]"},
    {"name": "WalletConnect Project ID",             "severity": "medium",   "group": "Web3",
     "regex": r"(?i)walletconnect.{0,25}project.?id.{0,10}['\"]([a-f0-9]{32})['\"]"},
    {"name": "Alchemy API Key",                      "severity": "critical", "group": "Web3",
     "regex": r"(?i)alchemy.{0,25}api.?key.{0,10}['\"]([A-Za-z0-9_\-]{32})['\"]"},
    {"name": "Infura Project Secret",                "severity": "critical", "group": "Web3",
     "regex": r"(?i)infura.{0,25}project.?secret.{0,10}['\"]([A-Za-z0-9]{32})['\"]"},
    {"name": "Moralis API Key",                      "severity": "critical", "group": "Web3",
     "regex": r"(?i)moralis.{0,25}api.?key.{0,10}['\"]([A-Za-z0-9]{64,})['\"]"},
    {"name": "Laravel APP_KEY",                      "severity": "critical", "group": "Framework",
     "regex": r"base64:[A-Za-z0-9+/]{43}="},
    {"name": "Django Secret Key",                    "severity": "critical", "group": "Framework",
     "regex": r"(?i)django.{0,15}secret.{0,10}key.{0,10}['\"]([^'\"]{40,})['\"]"},
    {"name": "Rails Secret Key Base",                "severity": "critical", "group": "Framework",
     "regex": r"(?i)secret.?key.?base.{0,10}['\"]([a-f0-9]{128})['\"]"},
    {"name": "NextAuth Secret",                      "severity": "critical", "group": "Framework",
     "regex": r"(?i)(?:nextauth|next_auth).?secret.{0,10}['\"]([^'\"]{20,})['\"]"},
    {"name": "Vite VITE_ Secret",                    "severity": "high",     "group": "Framework",
     "regex": r"VITE_[A-Z_]{3,40}\s*[:=]\s*['\"]([^'\"]{10,200})['\"]"},
    {"name": "reCAPTCHA Site Key",                   "severity": "low",      "group": "Google",
     "regex": r"6[0-9A-Za-z_\-]{38}"},
    {"name": "reCAPTCHA Secret Key",                 "severity": "critical", "group": "Google",
     "regex": r"(?i)recaptcha.{0,25}secret.{0,10}['\"]([0-9A-Za-z_\-]{40})['\"]"},
    {"name": "Internal IP Address",                  "severity": "low",      "group": "Network",
     "regex": r"(?:^|[^0-9])(?:10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|172\.(?:1[6-9]|2[0-9]|3[01])\.[0-9]{1,3}\.[0-9]{1,3}|192\.168\.[0-9]{1,3}\.[0-9]{1,3})(?:[^0-9]|$)"},
    {"name": "SMTP Password",                        "severity": "critical", "group": "Email",
     "regex": r"(?i)smtp.{0,25}(?:pass|password|pwd).{0,10}['\"]([^'\"]{6,100})['\"]"},
    {"name": "GraphQL Endpoint",                     "severity": "low",      "group": "Endpoints",
     "regex": r"['\"](?:https?://[^'\"]+)?/graphql[/?'\"]"},
    {"name": "Pulumi Access Token",                  "severity": "critical", "group": "DevOps",
     "regex": r"pul-[a-f0-9]{40}"},
    {"name": "Shippo API Key",                       "severity": "critical", "group": "Logistics",
     "regex": r"shippo_(?:test|live)_[a-f0-9]{40}"},
    {"name": "EasyPost API Key",                     "severity": "critical", "group": "Logistics",
     "regex": r"EZ[A-Za-z0-9]{36}"},
    {"name": "Expensify API Secret",                 "severity": "critical", "group": "Finance",
     "regex": r"(?i)expensify.{0,25}(?:api.?secret|credential).{0,10}['\"]([A-Za-z0-9]{32})['\"]"},
    {"name": "Rippling API Token",                   "severity": "critical", "group": "HR",
     "regex": r"(?i)rippling.{0,25}(?:api.?token|token).{0,10}['\"]([A-Za-z0-9_\-]{32,})['\"]"},
    {"name": "Lever API Key",                        "severity": "critical", "group": "HR",
     "regex": r"(?i)lever.{0,25}api.?key.{0,10}['\"]([A-Za-z0-9\-]{36})['\"]"},
    {"name": "Weaviate API Key",                     "severity": "critical", "group": "AI",
     "regex": r"(?i)weaviate.{0,25}api.?key.{0,10}['\"]([A-Za-z0-9]{32,})['\"]"},
    {"name": "Zapier Webhook",                       "severity": "high",     "group": "Automation",
     "regex": r"https://hooks\.zapier\.com/hooks/catch/[0-9]+/[a-zA-Z0-9]+"},
    {"name": "Make (Integromat) Webhook",            "severity": "high",     "group": "Automation",
     "regex": r"https://hook\.(?:eu|us)[0-9]*\.make\.com/[a-zA-Z0-9]{32}"},
    {"name": "Workato Webhook",                      "severity": "high",     "group": "Automation",
     "regex": r"https://www\.workato\.com/webhooks/rest/[a-f0-9\-]{36}/[a-zA-Z0-9\-]+"},
    {"name": "Encryption Key Hex",                   "severity": "high",     "group": "Cryptography",
     "regex": r"(?i)(?:encryption|cipher|aes|des|hmac).{0,20}key.{0,10}['\"]([a-f0-9]{32,64})['\"]"},
]

SEVERITY_ORDER = {"critical": 4, "high": 3, "medium": 2, "low": 1}


def compile_patterns(disable=None, extra_file=None):
    disable = disable or []
    active = [p for p in PATTERNS if p["name"] not in disable]
    if extra_file:
        with open(extra_file) as fh:
            active.extend(json.load(fh))
    compiled = []
    for p in active:
        try:
            compiled.append((p, re.compile(p["regex"], re.MULTILINE | re.DOTALL)))
        except re.error:
            pass
    return compiled
