from __future__ import annotations
import re

_CHECKS = [
    ("eval() sink",                 "high",     "DOM XSS",
     r"""\beval\s*\(\s*(?!['"`])([a-zA-Z_$][a-zA-Z0-9_$.\[\]'"+\s]{1,200})\)""",
     "eval() called with dynamic input"),
    ("innerHTML from variable",     "high",     "DOM XSS",
     r"""\.innerHTML\s*[+]?=\s*(?!['"`][^'"`;]{0,5}['"`])""",
     "innerHTML set from potentially untrusted source"),
    ("outerHTML from variable",     "high",     "DOM XSS",
     r"""\.outerHTML\s*[+]?=\s*(?!['"`])""",
     "outerHTML set from potentially untrusted source"),
    ("document.write sink",         "high",     "DOM XSS",
     r"""document\.write(?:ln)?\s*\(""",
     "document.write/writeln with dynamic content"),
    ("setTimeout string eval",      "medium",   "DOM XSS",
     r"""setTimeout\s*\(\s*(?:[a-zA-Z_$][a-zA-Z0-9_$]*\s*\+|`[^`]*\$\{)""",
     "setTimeout with dynamic string — equivalent to eval()"),
    ("setInterval string eval",     "medium",   "DOM XSS",
     r"""setInterval\s*\(\s*(?:[a-zA-Z_$][a-zA-Z0-9_$]*\s*\+|`[^`]*\$\{)""",
     "setInterval with dynamic string — equivalent to eval()"),
    ("dangerouslySetInnerHTML",     "high",     "DOM XSS",
     r"""dangerouslySetInnerHTML\s*=\s*\{""",
     "React dangerouslySetInnerHTML — XSS if not sanitized"),
    ("insertAdjacentHTML sink",     "high",     "DOM XSS",
     r"""\.insertAdjacentHTML\s*\(""",
     "insertAdjacentHTML with dynamic content"),
    ("Function() constructor",      "high",     "DOM XSS",
     r"""\bnew\s+Function\s*\(""",
     "Function constructor used — equivalent to eval()"),
    ("jQuery .html() sink",         "medium",   "DOM XSS",
     r"""\$\([^)]+\)\.html\s*\([^'"]\s*[^)]*\)""",
     "jQuery .html() called with dynamic data"),
    ("jQuery .append/.prepend dynamic", "medium", "DOM XSS",
     r"""\$\([^)]+\)\.(?:append|prepend|after|before|replaceWith)\s*\([^'"'`]""",
     "jQuery DOM manipulation with potentially untrusted input"),
    ("location.href from input",    "medium",   "Open Redirect",
     r"""(?:location\.href|location\.replace|window\.location)\s*=\s*(?:(?:decodeURI|atob|unescape)\s*\(|[a-zA-Z_$][a-zA-Z0-9_$]*\s*(?:\+|\.))""",
     "Location redirected from potentially untrusted source"),
    ("document.domain assignment",  "medium",   "DOM XSS",
     r"""document\.domain\s*=""",
     "document.domain assignment weakens same-origin policy"),
    ("srcdoc attribute dynamic",    "high",     "DOM XSS",
     r"""\.setAttribute\s*\(\s*['"]srcdoc['"]""",
     "srcdoc attribute set dynamically — XSS vector"),
    ("__proto__ assignment",        "critical", "Prototype Pollution",
     r"""\[['"]__proto__['"]\]\s*=""",
     "Direct __proto__ assignment — prototype pollution"),
    ("constructor.prototype access","high",     "Prototype Pollution",
     r"""\.constructor\.prototype\s*(?:\[|\.(?!call|apply|bind))""",
     "constructor.prototype manipulation"),
    ("merge/assign with __proto__", "medium",   "Prototype Pollution",
     r"""function\s+(?:merge|deepMerge|assign|extend|deepExtend|defaults)\s*\([^)]*\)\s*\{[^}]{0,500}(?:__proto__|prototype)""",
     "Recursive merge may be prototype pollution vector"),
    ("Object.assign from request",  "low",      "Prototype Pollution",
     r"""Object\.assign\s*\(\s*(?:target|obj|config|options|props|settings)\s*,\s*(?:body|params|query|data|req\.)""",
     "Object.assign with potentially user-controlled source"),
    ("cloud metadata endpoint",     "critical", "SSRF",
     r"""(?:fetch|axios|request|XMLHttpRequest|http\.get)\s*\(?['"`](?:https?://)?(?:169\.254\.169\.254|metadata\.google\.internal|169\.254\.170\.2|fd00:ec2::254)[^'"` \)]*['"`]""",
     "Code fetches cloud metadata — SSRF / credential theft"),
    ("SSRF via URL parameter",      "high",     "SSRF",
     r"""(?:fetch|axios|request|got|superagent)\s*\(\s*(?:req\.|request\.|query\.|params\.|body\.|searchParams\.get|url|href|urlParam)""",
     "Fetching URLs from request parameters — potential SSRF"),
    ("hardcoded internal fetch",    "medium",   "SSRF",
     r"""(?:fetch|axios)\s*\(?['"`]https?://(?:localhost|127\.0\.0\.1|0\.0\.0\.0|10\.\d+\.\d+\.\d+|172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+|192\.168\.\d+\.\d+)""",
     "Hardcoded internal/loopback URL call"),
    ("CORS wildcard origin",        "medium",   "CORS",
     r"""(?:Access-Control-Allow-Origin|allowedOrigins?)\s*[:=]\s*['"`]\*['"`]""",
     "Wildcard CORS origin — any site can read responses"),
    ("CORS reflect request origin", "high",     "CORS",
     r"""(?:Access-Control-Allow-Origin|origin)\s*[:=]\s*(?:req\.headers?\.origin|request\.origin|headers\[['"]origin)""",
     "CORS origin reflected from request — misconfiguration"),
    ("CORS credentials + wildcard", "critical", "CORS",
     r"""Access-Control-Allow-Credentials.*true.*Access-Control-Allow-Origin.*\*|Access-Control-Allow-Origin.*\*.*Access-Control-Allow-Credentials.*true""",
     "Credentials + wildcard origin — critical CORS misconfiguration"),
    ("postMessage no origin check", "medium",   "PostMessage",
     r"""addEventListener\s*\(\s*['"]message['"]""",
     "postMessage listener — verify origin is validated"),
    ("postMessage to wildcard",     "medium",   "PostMessage",
     r"""\.postMessage\s*\([^,]+,\s*['"`]\*['"`]""",
     "postMessage sent to wildcard origin"),
    ("JWT in localStorage",         "high",     "Insecure Storage",
     r"""localStorage\.(?:setItem|getItem)\s*\(\s*['"`](?:jwt|access_token|refresh_token|id_token|bearer|token)[^'"` ]*['"`]""",
     "JWT stored in localStorage — stolen by XSS"),
    ("sensitive key in localStorage","medium",  "Insecure Storage",
     r"""localStorage\.setItem\s*\(\s*['"`](?:token|auth|session|password|secret|key|credential)[^'"` ]*['"`]""",
     "Sensitive data in localStorage — accessible to XSS"),
    ("exec with user input",        "critical", "RCE",
     r"""(?:exec|execSync|spawn|spawnSync|execFile|execFileSync)\s*\(\s*(?:[`'"][^'"`]*\$\{|req\.|body\.|params\.|query\.|user\.)""",
     "OS command execution with user-controlled input — RCE"),
    ("require() with user input",   "critical", "RCE",
     r"""require\s*\(\s*(?:req\.|body\.|params\.|query\.|user\.)""",
     "require() with user input — arbitrary module load"),
    ("fs.readFile user path",       "high",     "Path Traversal",
     r"""fs\.(?:readFile|writeFile|appendFile|createReadStream|createWriteStream|readFileSync|writeFileSync)\s*\(\s*(?:req\.|body\.|params\.|query\.)""",
     "File system access with user-controlled path"),
    ("path.join with user input",   "high",     "Path Traversal",
     r"""path\.(?:join|resolve|normalize)\s*\([^)]*(?:req\.|body\.|params\.|query\.)""",
     "path.join with user input — path traversal"),
    ("raw SQL concatenation",       "critical", "SQL Injection",
     r"""(?:query|execute|db\.run|connection\.query|pool\.query)\s*\(\s*['"`]?\s*(?:SELECT|INSERT|UPDATE|DELETE|DROP|UNION)[^;'"` ]{0,200}\+""",
     "SQL query built with string concatenation"),
    ("template literal SQL",        "high",     "SQL Injection",
     r"""(?:query|execute|db\.run|connection\.query|pool\.query)\s*\(\s*`(?:SELECT|INSERT|UPDATE|DELETE|DROP|UNION)[^`]{0,500}\$\{""",
     "SQL query uses template literals — injection if user-controlled"),
    ("JWT none algorithm",          "critical", "JWT",
     r"""(?:algorithm|alg)\s*[:=]\s*['"`]none['"`]""",
     "JWT accepts 'none' algorithm — token forgery"),
    ("JWT without verification",    "critical", "JWT",
     r"""jwt\.decode\s*\(\s*[^,)]+\)\s*(?:;|$)""",
     "JWT decoded without signature verification"),
    ("weak JWT secret",             "high",     "JWT",
     r"""jwt\.sign\s*\([^,]+,\s*['"`](?:secret|password|test|dev|123456|your_secret|changeme|jwt_secret|mysecret)[^'"` ]*['"`]""",
     "JWT signed with weak hardcoded secret"),
    ("node-serialize deserialization","critical","RCE",
     r"""serialize\.unserialize\s*\(""",
     "node-serialize unserialize — known RCE vulnerability"),
    ("eval in template engine",     "critical", "SSTI",
     r"""(?:ejs|pug|jade|handlebars|nunjucks|swig)\.(?:render|compile)\s*\(\s*(?:req\.|body\.|params\.|query\.)""",
     "Template engine renders user input — Server-Side Template Injection"),
    ("open redirect via param",     "medium",   "Open Redirect",
     r"""res\.redirect\s*\(\s*(?:req\.|body\.|params\.|query\.|url|href)""",
     "res.redirect with user-controlled URL"),
    ("RegExp from user input",      "medium",   "ReDoS",
     r"""new\s+RegExp\s*\(\s*(?:req\.|body\.|params\.|query\.)""",
     "RegExp constructed from user input — ReDoS possible"),
    ("XML/HTML entity injection",   "medium",   "XXE",
     r"""(?:libxmljs|xml2js|DOMParser|XMLParser).*(?:req\.|body\.|params\.|query\.)""",
     "XML parsed from user input — XXE if external entities enabled"),
]

_COMPILED = [
    (name, sev, cat, re.compile(pattern, re.DOTALL | re.I), desc)
    for name, sev, cat, pattern, desc in _CHECKS
]


def run_security_checks(content: str, source_url: str) -> list[dict]:
    findings = []
    for name, sev, cat, regex, desc in _COMPILED:
        for match in regex.finditer(content):
            line = content[:match.start()].count("\n") + 1
            cs   = max(0, match.start() - 100)
            ce   = min(len(content), match.end() + 100)
            findings.append({
                "pattern":          name,
                "severity":         sev,
                "group":            cat,
                "category":         cat,
                "value":            match.group(0)[:200],
                "source_url":       source_url,
                "line":             line,
                "context":          content[cs:ce],
                "description":      desc,
                "type":             "security_check",
                "confidence_score": 72,
                "confidence_label": "likely",
            })
    return findings
